---
- name: Teardown of Azure resources
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group.value }}"
        force: True
        state: absent

    - name: Delete a record set
      azure_rm_dnsrecordset:
        resource_group: "{{ dnsRG.value }}" #Hard coding resource group due to not passing from pipeline
        record_type: "{{ dnsRecord.value }}"
        relative_name: "t24-{{ env_name.value }}"
        zone_name: "{{ dnsZone.value }}"
        state: absent


    #- name: Remove vm
    #  azure_rm_virtualmachine:
    #    resource_group: "{{ resource_group.value }}"
    #    name: "{{ env_name.value +'1' }}"
    #    state: absent 

    #- name: sleep for 300 seconds and continue with play
    #  wait_for: timeout=300
  
    #- name: Remove account
    #  azure_rm_storageaccount:
    #    resource_group: "{{ resource_group.value }}"
    #    name: "{{ env_name.value }}"
    #    state: absent

    #- name: Remove network interface
    #  azure_rm_networkinterface:
    #    resource_group: "{{ resource_group.value }}"
    #    name: "{{ env_name.value +'1' }}"
    #    state: absent