---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        deployment_name: "{{ Environment.value }}"
        state: present
        location: "{{ Region.value }}"
        resource_group_name: "{{ ResourceGroup.value }}"
        parameters:
          ResourceGroup:
            value: "{{ ResourceGroup.value }}"
          Region:
            value: "{{ Region.value }}"
          virtualNetworkName:
            value: "{{ virtualNetworkName.value }}"
          virtualNetworkResourceGroup:
            value: "{{ virtualNetworkResourceGroup.value }}"
          SubnetName:
            value: "{{ SubnetName.value }}"
          Environment:
            value: "{{ Environment.value }}"
          StorageAccountName:
            value: "{{ StorageAccountName.value }}"
          NsgResourceGroup:
            value: "{{ NsgResourceGroup.value }}"
          NsgName:
            value: "{{ NsgName.value }}"
        template: "{{ lookup('file','../../CAF-Azure-Templates/caf_test_server.json') | from_json }}"

